markdown: kramdown
permalink: /:categories/:year/:title/
paginate: 5
paginate_path: /blog/page:num/
exclude:
  - package.json
  - node_modules
sass:
  load_paths:
    - _sass
    - node_modules
defaults:
  -
    scope:
      type: posts
    values:
      layout: blog
      categories: blog
plugins:
  - jekyll-paginate
  - jekyll_asset_pipeline
